/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.0.2-18-g3e6cec1286-20240919"
#endif /* AVUTIL_FFVERSION_H */
